airports = [
    {"icao": "KJFK", "name": "John F. Kennedy International Airport", "city": "New York", "timezone": "America/New_York"},
    {"icao": "EGLL", "name": "Heathrow Airport", "city": "London", "timezone": "Europe/London"},
    {"icao": "LFPG", "name": "Charles de Gaulle Airport", "city": "Paris", "timezone": "Europe/Paris"},
    {"icao": "OMDB", "name": "Dubai International Airport", "city": "Dubai", "timezone": "Asia/Dubai"},
    {"icao": "RJTT", "name": "Haneda Airport", "city": "Tokyo", "timezone": "Asia/Tokyo"},
    {"icao": "UUEE", "name": "Шереметьево", "city": "Москва", "timezone": "Europe/Moscow"},
    {"icao": "UUWW", "name": "Внуково", "city": "Москва", "timezone": "Europe/Moscow"},
    {"icao": "UUDD", "name": "Домодедово", "city": "Москва", "timezone": "Europe/Moscow"},
    {"icao": "ULLI", "name": "Пулково", "city": "Санкт-Петербург", "timezone": "Europe/Moscow"},
    {"icao": "URSS", "name": "Аэропорт Сочи", "city": "Сочи", "timezone": "Europe/Moscow"},
    {"icao": "UNNT", "name": "Толмачёво", "city": "Новосибирск", "timezone": "Asia/Novosibirsk"},
    {"icao": "USSS", "name": "Кольцово", "city": "Екатеринбург", "timezone": "Asia/Yekaterinburg"},
    {"icao": "UWKD", "name": "Казань", "city": "Казань", "timezone": "Europe/Moscow"},
    {"icao": "URKK", "name": "Пашковский", "city": "Краснодар", "timezone": "Europe/Moscow"},
    {"icao": "UOOO", "name": "Новый Уренгой", "city": "Новый Уренгой", "timezone": "Asia/Yekaterinburg"},
    {"icao": "UNKL", "name": "Емельяново", "city": "Красноярск", "timezone": "Asia/Krasnoyarsk"},
    {"icao": "URMM", "name": "Минеральные Воды", "city": "Минеральные Воды", "timezone": "Europe/Moscow"},
    {"icao": "UHHH", "name": "Хабаровск", "city": "Хабаровск", "timezone": "Asia/Vladivostok"},
    {"icao": "UHWW", "name": "Владивосток", "city": "Владивосток", "timezone": "Asia/Vladivostok"},
    {"icao": "URMT", "name": "Ставрополь", "city": "Ставрополь", "timezone": "Europe/Moscow"},
    {"icao": "URRP", "name": "Платов", "city": "Ростов-на-Дону", "timezone": "Europe/Moscow"},
    {"icao": "UWPS", "name": "Бегишево", "city": "Набережные Челны", "timezone": "Europe/Moscow"},
    {"icao": "UWWW", "name": "Курумоч", "city": "Самара", "timezone": "Europe/Samara"},
    {"icao": "UWUU", "name": "Магнитогорск", "city": "Магнитогорск", "timezone": "Asia/Yekaterinburg"},
]